# Generated by Django 5.0.6 on 2024-07-09 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='markdowncontent',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
